USE [master]
GO

CREATE DATABASE [SuperheroesDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SuperheroesDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SuperheroesDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SuperheroesDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SuperheroesDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SuperheroesDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SuperheroesDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SuperheroesDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SuperheroesDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SuperheroesDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SuperheroesDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [SuperheroesDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SuperheroesDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SuperheroesDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SuperheroesDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SuperheroesDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SuperheroesDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SuperheroesDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SuperheroesDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SuperheroesDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SuperheroesDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SuperheroesDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SuperheroesDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SuperheroesDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SuperheroesDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SuperheroesDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SuperheroesDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SuperheroesDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SuperheroesDB] SET RECOVERY FULL 
GO

ALTER DATABASE [SuperheroesDB] SET  MULTI_USER 
GO

ALTER DATABASE [SuperheroesDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SuperheroesDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SuperheroesDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SuperheroesDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SuperheroesDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SuperheroesDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SuperheroesDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SuperheroesDB] SET  READ_WRITE 
GO


